version: '3.9'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes: 
      - db:/var/lib/postdgresql/data
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${LOCAL_PORT}:8080"
    depends_on:
      - postgres
volumes:
  db:
    driver: local