version: '3.9'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KUMULUZEE_ENV_NAME=${ENVIRONMENT}
      - KUMULUZEE_NAME=${MICROSERVICE_NAME}
      - KUMULUZEE_DATASOURCES0_USERNAME=${POSTGRES_USER}
      - KUMULUZEE_DATASOURCES0_PASSWORD=${POSTGRES_PASSWORD}
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      - KUMULUZEE_CONFIG_CONSUL_AGENT=${CONSUL_URL}
    ports:
      - "127.0.0.1:${LOCAL_PORT}:8080"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

networks:
  default:
    name: local.rso.com
    ipam:
      driver: default
      config:
        - subnet: 10.100.1.0/24
