version: '3.9'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KUMULUZEE_ENV_NAME=${ENVIRONEMNT}
      - KUMULUZEE_NAME=${MICROSERVICE_NAME}
      - KUMULUZEE_DATASOURCES0_USERNAME=${POSTGRES_USER}
      - KUMULUZEE_DATASOURCES0_PASSWORD=${POSTGRES_PASSWORD}
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    ports:
      - "127.0.0.1:${LOCAL_PORT}:8080"
    depends_on:
      - postgres
