apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailing-microservice
  template:
    metadata:
      labels:
        app: mailing-microservice
    spec:
      containers:
        - image: rsouser/mailing-microservice
          name: mailing-microservice
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_name
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_user
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gke-rso-secrets
                  key: db_pass
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://${HOST_IP}:8500
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: mailing-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: mailing-microservice