kumuluzee:
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/MailDS
      max-pool-size: 20
      connection-url: jdbc:postgresql://localhost:5432/rso_db
      username: dbuser
      password: postgres